### ISSUE TITLE
Add a version of runN that generates CUDA code which can be debugged

### ISSUE THREAD

**Issue by noahmartinwilliams** [AccelerateHS/accelerate-llvm#101]
The code I'm writing that uses this library doesn't seem to use the GPU very much, and I'd like to be able to troubleshoot it better.
If I could generate cuda code that has debugging symbols in it then I could probably use cuda-gdb to see why it's so slow.

If there was some sort of runN function that generated CUDA code that could be debugged with cuda-gdb or something similar then that would probably be helpful.

I've tried digging around in the code for ptx code generation, but there's a lot of stages to it to check, and the fact that the code running on the GPU is kind of opaque is a bit annoying to deal with.

My GPU is an NVidia GeForce RTX 3050 Laptop GPU, and I'm running the latest version of arch linux.

**Comment by tmcdonell** [comment]
Hi Noah,

This is possible already. You need:
1. A [debug](https://github.com/tmcdonell/accelerate/blob/master/accelerate.cabal#L210) build of `accelerate`
1. Add the [`debug`](https://github.com/tmcdonell/accelerate/blob/master/accelerate.cabal#L273) flag when running your program (on the command line, or set the `ACCELERATE_FLAGS` environment variable)

However, you'll probably find that it is not really useful:
* There is no source location information, so figuring out what is going on in the debugger will be a challenge (I have a proof of concept for source location information, but it still needs a lot of work)
* It sounds like your problem is not that the generated kernels are slow, but that you are spending most of your time not executing code on the GPU, but stuck somewhere in Haskell land (either generating the kernel program, or maybe in the Accelerate RTS, or stuck in Haskell's GC, or..., but it's unclear what. Again I had a proof of concept of outputting profiling data, but that again still needs a lot of work)

If you are using `runN` correctly (i.e. it is not re-compiling on subsequent invocations: this is easiest to check with the [`dump-phases`](https://github.com/tmcdonell/accelerate/blob/master/accelerate.cabal#L277) flag), that probably means an Accelerate RTS problem. In that case a small reproducer would help isolate the problem.

**Comment by noahmartinwilliams** [comment]
After tinkering with my project a bit, I've found out that it was trying to load up all the data from a file before even touching the GPU (which is why I thought it wasn't using the GPU enough). Now it seems to be running at a much higher percentage. :/

**Comment by tmcdonell** [comment]
Okay I guess this can be closed for now then? Feel free to reopen/start a new issue if you have problems.
In general, I first reach for `-ddump-phases` to get an idea of what is going on, and dig in from there. Maybe that will help you as well.
