### ISSUE TITLE
Stackage Availability

### ISSUE THREAD

**Issue by SamuelSchlesinger** [AccelerateHS/accelerate-llvm#11]
Are there plans to put these packages on Stackage?

**Comment by tmcdonell** [comment]
Yes, that would be good.

I think, the primary question will be getting the LLVM bindings onto Stackage. I'm currently using `llvm-general`, but that seems to have fallen into questionable maintenance status. I recently discovered a fork at [`llvm-hs`](https://github.com/llvm-hs/llvm-hs), which seems to be active, so I am considering switching to use that instead. You should ask if they have plans for Stackage...

**Comment by LeanderK** [comment]
an issue (llvm-hs/llvm-hs#58) about putting llvm-hs on stockage was created 2 days ago

**Comment by cocreature** [comment]
fyi `llvm-hs` is now on stackage.

**Comment by tmcdonell** [comment]
- [ ] unique https://github.com/ekmett/unique/issues/1
 - [ ] chaselev-deque https://github.com/rrnewton/haskell-lockfree/issues/63
 - [ ] libffi (who maintains this? GHC already includes libFFI inside of it, so maybe we can use that, if there are hooks to it through the ghc-api or otherwise)
 - [ ] cuda
 - [ ] nvvm

**Comment by RyanGlScott** [comment]
@remiturk is the maintainer of `libffi`: https://github.com/remiturk/libffi

Also, I'm not aware of any GHC API hooks to `libffi`.

**Comment by tmcdonell** [comment]
Should be in stackage nightly soon. https://github.com/fpco/stackage/pull/2880
