### ISSUE TITLE
Cabal 3.8.1.0 build failed.

### ISSUE THREAD

**Issue by npatsakula** [AccelerateHS/accelerate-llvm#88]
**Description**

Hello! I failed to build `accelerate-llvm` using latest Cabal: [issue](https://github.com/haskell/cabal/issues/8635). After little investigation we figure out that problem in `post-checkout-command`: [link](https://github.com/haskell/cabal/issues/8635#issuecomment-1353576762).

**Steps to reproduce**

1. Install `Cabal 3.8.1.0` (e.g. using `ghcup`).
2. Run `cabal build`

**Additional context**

Looks like it was a bug in Cabal that forced to use this workaround in the first place. I can make patch that fixing this issue if it would be appropriate.

**Comment by dpvanbalen** [comment]
Thank you! It would be good to test which versions of Cabal still need that workaround. If no recent-enough versions do, we could simply remove it and raise the bounds on cabal-version. Otherwise; is it possible to add (CPP) conditions to branch on the cabal-version? It would be best if we could keep supporting slightly-less recent versions of Cabal without complicating the setup process even more.

**Comment by robbert-vdh** [comment]
I replied here: https://github.com/haskell/cabal/issues/8635#issuecomment-1354731726

The negation was needed for Cabal <3.8, and according to ghcup 3.6.x is still the recommended version. I guess they fixed the bug in 3.8 bug that now breaks backwards compatibility.

**Comment by tmcdonell** [comment]
I believe this is fixed now, so closing. Thanks for your patience!
